### PR TITLE
Common Missing Addr Abbrevations

### PR DESCRIPTION
**Pull request by ingalls**
Tracking a bunch of discovered missing address level abbreviations

### CODE REVIEW

**Comment by KaiBot3000** [comment]
👋 added on 
- [x] `Cam` -> `Camino` (confirmed this is a standard abbrv using other sources)
- [x] `Co` -> `County` as in `County Highway` -> `Co Hwy` (didn't see this one in official docs but it's very common in our US data)

**Comment by KaiBot3000** [comment]
Some tokens I'm noticing in US address data:
- RESV -> Reservoir
- CMNS -> Commons (we have the singular, only)
- ANX -> Annex
- LA -> Lane

Not sure whether they're common enough to add just yet.

**Comment by lizziegooding** [comment]
Common tokens I'm seeing in US addresses:
- `BLV` -> Boulevard
- `NO` -> North
- `SO` -> South

I didn't add this in my latest commit, but I'm wondering if we would consider adding tokens for `MLK` -> (Dr) Martin Luther King (Jr).

**Comment by lizziegooding** [comment]
After syncing with @ingalls, removing `No` and `So` as token replacers and instead including those tokens in individual sources as necessary to reduce noise. Per sync with the rest of the team, accounting for street names with common abbreviations like `MLK`, `JFK`, `LBJ` would be better served by adding these as synonyms rather than tokens.

**Comment by ingalls** [comment]
Tracking: https://github.com/mapbox/geocoder-abbreviations/pull/30

**Pull request closed without merging**
